version: '3.8'

volumes:
  frtnd:
    driver: local
    driver_opts:
      type: none
      device: .
      o: bind

services:
  frontend:
    container_name: "frontend"

    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "5173:5173"

    volumes:
      - frtnd:/app
      - /app/node_modules
